config:
  logLevel: debug
  metricsNamePrefix: 'event_exporter_'
  logFormat: json
  receivers:
    # - name: dump
    #   file:
    #   layout: {}
    #   path: /dev/stdout
    - name: loki
      loki:
        streamLabels:
          app: kubernetes-event-exporter
          dataCenter: local-cluster
        url: http://$LOKI_URL:3100/loki/api/v1/push
        # layout:
        #   message: "{{ .Message }}"
        #   reason: "{{ .Reason }}"
        #   type: "{{ .Type }}"
        #   count: "{{ .Count }}"
        #   kind: "{{ .InvolvedObject.Kind }}"
        #   name: "{{ .InvolvedObject.Name }}"
        #   namespace: "{{ .Namespace }}"
        #   component: "{{ .Source.Component }}"
        #   host: "{{ .Source.Host }}"
  route:
    routes:
    # - match:
    #   - receiver: dump
    - match:
      - receiver: loki